language: go
go:
  - 1.9.1
cache:
  directories:
    - "$HOME/coding/google-cloud-sdk"
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS-~/gcloud-service-key.json
    - PROJECT_NAME=serene-188901
    - CLUSTER_NAME=serene
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    
before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta
  # - gcloud docker -- pull gcr.io/serene-188901/dash-ui:latest
  
install:
  - sudo docker build -t test/build .
  - npm install -g react-scripts
# TODO; implement test coverage check
script:
  - echo "TESTINGGGGGGGGGGGG"
  - git clone https://github.com/facebook/watchman.git
  - pushd watchman
  - sudo apt-get install -y autoconf automake build-essential python-dev
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - echo "WATCHMANNNN VERSION"
  - watchman --version
  - popd
  - ls
  - npm test
  # - go test ./... -tags dev -v
  # - goreporter -p ./ -r ./reports -e -f text
before_deploy:
  - gcloud --quiet components update kubectl
deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
      

# notifications:
  # slack: effortlessrental:W1T5KZKXVJXg9WraZTGx0VDh