language: node_js
sudo: required
cache:
  directories:
    - "$HOME/coding/google-cloud-sdk/"
    

# Install services
services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS-~/gcloud-service-key.json
    - PROJECT_NAME=serene-188901
    - CLUSTER_NAME=serene
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - NODE_ENV=CI    

install:
  - npm install

before_install:
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
       curl https://sdk.cloud.google.com | bash;
    fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta


before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
      