
language: node_js

node_js:
- 'stable'

# To test Node v4, Travis needs to use a newer C++ compiler.
# Source: https://github.com/nodejs/nan/issues/435#issuecomment-136063745
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
- export CXX=g++-4.8
- "$CXX --version"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS-~/gcloud-service-key.json
    - PROJECT_NAME=serene-188901
    - CLUSTER_NAME=serene
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - NODE_ENV=CI    


before_install:
- openssl aes-256-cbc -K $encrypted_4e543ecb61f7_key -iv $encrypted_4e543ecb61f7_iv -in key.json.enc -out key.json -d


install:
  - npm install




before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

  # use the decrypted service account credentials to authenticate the command line tool
  # get the encrypted variable names from travis cli: https://docs.travis-ci.com/user/encrypting-files/
  - openssl aes-256-cbc -K $TRAVIS_ENCRYPTED_key -iv $TRAVIS_ENCRYPTED_iv -in gcloud-service-key.json.enc -out gcloud-service-key.json -d
  - gcloud auth activate-service-account --key-file gcloud-service-key.json

  - gcloud config set project PROJECT  

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
      