language: node_js
node_js: '4'
dist: trusty
sudo: false
git:
  depth: 1
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS-~/gcloud-service-key.json
  - PROJECT_NAME=serene-188901
  - CLUSTER_NAME=serene
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a
  - NODE_ENV=CI    
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
cache:
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
install:
  - travis_wait ./tools/travis/install-gc-sdk.sh
  - npm install
  - npm run clean

before_install:
  - gcloud version || true
  # - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta


before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: develop
      