apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dash-ui
spec:
  replicas: 2
  selector:
  template:
    metadata:
      labels:
        run: dash-ui
    spec:
      containers:
        - image: dash-ui
          name: dash-ui
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
